Repository fga-eps-mds/2023-1-Alectrion-FrontEnd, pull requests merged in 2023-05, with the labels that each got.

#4 41 cadastro de equipamento
  src/components/equipment-form/index.tsx
  src/components/equipment-register-modal/index.tsx
  src/components/form-fields/controlled-select/index.tsx
  src/components/form-fields/controlled-select/styles.tsx
  src/components/form-fields/date/index.tsx
  src/components/form-fields/input/index.tsx
  src/components/form-fields/text-area/index.tsx
  src/components/modal/index.tsx
  src/config/routes/Routes.tsx
  src/constants/equipment.ts
  src/pages/equipment-register/index.tsx
  src/pages/login/index.tsx
  src/services/api.ts
  src/services/requests/equipment/index.tsx
  src/services/requests/equipment/types.d.ts
  src/styles/Button.ts
Labels: US, MEDIUM, EPS, MDS

#3 ;#feat: 44 criar tela lista de equipamentos
  example.env
  package.json
  src/components/side-bar/index.tsx
  src/config/env.ts
  src/config/lib/axios/index.ts
  src/config/routes/Routes.tsx
  src/pages/equipaments/EquipamentsControl.tsx
  src/pages/equipaments/equipaments.spec.tsx
  src/pages/login/login.spec.tsx
Labels: US, MEDIUM, EPS, MDS

#7 79 listar e detalhar movimentação
  src/components/equipment-form/index.tsx
  src/components/form-fields/text-area/index.tsx
  src/components/modal/index.tsx
  src/components/movements-modal/index.tsx
  src/components/side-bar/index.tsx
  src/config/lib/axios/index.ts
  src/config/routes/Routes.tsx
  src/constants/movements.ts
  src/pages/equipaments/EquipamentsControl.tsx
  src/pages/equipaments/equipaments.spec.tsx
  src/pages/login/index.tsx
  src/pages/movements/MovementControl.tsx
  src/pages/movements/movements.spec.tsx
  src/services/api.ts
  src/services/requests/equipment/index.tsx
  src/styles/theme.ts
Labels: MINOR RELEASE

#8 FIX: Erro de build
  .github/workflows/code-analysis.yml
  src/components/form-fields/equipment/edit-equipment-form.tsx
  src/components/form-fields/equipment/equipment-form.tsx
  src/components/form-fields/equipment/equipment-select-field.tsx
  src/components/movements-modal/index.tsx
  src/config/routes/Routes.tsx
  src/pages/equipment-register/index.tsx
  src/pages/equipments/EquipamentsControl.tsx
  src/pages/movements/MovementControl.tsx
Labels: HOTFIX, DEVOPS, EPS, FIX RELEASE

#10 Fix - listagem movimentação
  src/components/movements-modal/index.tsx
  src/pages/equipments/EquipamentsControl.tsx
  src/pages/movements/MovementControl.tsx
Labels: HOTFIX

#14 84 - Criação de filtro de equipamentos
  package.json
  src/components/equipment-edit-modal/index.tsx
  src/components/equipment-view-form/index.tsx
  src/components/equipment-view-modal/index.tsx
  src/components/form-fields/controlled-select/index.tsx
  src/components/form-fields/controlled-select/styles.tsx
  src/components/form-fields/date/index.tsx
  src/components/form-fields/input/index.tsx
  src/config/lib/axios/index.ts
  src/config/routes/Routes.tsx
  src/constants/equipment.ts
  src/pages/equipments/EquipmentsControl.tsx
  src/pages/equipments/equipments.spec.tsx
  yarn-error.log
  yarn.lock
Labels: MINOR RELEASE

#12 81 - Adicionar Filtros de Movimentação
  src/components/form-fields/controlled-select/index.tsx
  src/components/form-fields/controlled-select/styles.tsx
  src/components/form-fields/date/index.tsx
  src/components/form-fields/input/input.spec.tsx
  src/components/form-fields/text-area/index.tsx
  src/components/form-fields/text-area/text-area.spec.tsx
  src/constants/movements.ts
  src/pages/movements/MovementControl.tsx
  src/pages/movements/movements.spec.tsx
  src/types/types.d.ts
  src/utils/toast.spec.tsx
Labels: FEATURE, MEDIUM, EPS, MDS, MINOR RELEASE

#16 80 registrar movimentacao
  package.json
  src/components/movement-form/index.tsx
  src/components/movement-register-modal/index.tsx
  src/components/movements-modal/index.tsx
  src/config/routes/Routes.tsx
  src/constants/movements.ts
  src/pages/movements/MovementControl.tsx
  yarn-error.log
  yarn.lock
Labels: FEATURE, MINOR RELEASE

#19 94 excluir movimentacao
  src/components/form-fields/controlled-select/styles.tsx
  src/components/form-fields/date/index.tsx
  src/components/movement-form/index.tsx
  src/pages/equipments/EquipmentsControl.tsx
  src/pages/movements/MovementControl.tsx
Labels: FEATURE, MAJOR RELEASE

#20 #108 FIX: alinhamento do botão de cadastro de movimentação
  src/pages/movements/MovementControl.tsx
Labels: HOTFIX, EASY, FIX RELEASE

#22 108 bug botao movimentacao
  src/components/movements-modal/index.tsx
  src/pages/movements/MovementControl.tsx
Labels: HOTFIX, FIX RELEASE

#23 #106 FIX: Resolve tamanho da linha ao cadastrar 1 item
  src/pages/equipments/EquipmentsControl.tsx
  src/pages/movements/MovementControl.tsx
Labels: HOTFIX, EASY, FIX RELEASE

#26 #110 fix: validação numero de série
  src/components/equipment-edit-form/index.tsx
  src/components/equipment-form/index.tsx
Labels: FIX RELEASE
