Repository fga-eps-mds/2023-1-Alectrion-FrontEnd, pull requests merged in 2023-06, with the labels that each got.

#31 #115 fix: cadastro de movimentação
  src/components/movement-form/index.tsx
Labels: FIX RELEASE

#33 #117 FIX: Adiciona botão para apagar filtros
  src/components/form-fields/controlled-select/index.tsx
  src/pages/equipments/EquipmentsControl.tsx
  src/pages/movements/MovementControl.tsx
Labels: HOTFIX, EASY, FIX RELEASE

#24 #107 fix: adiciona modal de movimentacao a partir da tela de equipame…
  src/components/movement-form/index.tsx
  src/components/movement-register-modal/index.tsx
  src/pages/equipments/EquipmentsControl.tsx
Labels: HOTFIX, FIX RELEASE

#34 #103 filtro ordem servico
  src/pages/order-service/OrderServiceControl.tsx
Labels: US, MDS, MINOR RELEASE

#35 119 gerar termo responsabilidade
  package.json
  public/PoliciaCivilLogo.jpeg
  src/components/action-buttons/back-button/index.tsx
  src/components/action-buttons/confirm-edit-button/index.tsx
  src/components/action-buttons/delete-extensive-button/index.tsx
  src/components/movement-form/index.tsx
  src/components/movement-register-modal/index.tsx
  src/components/movements-modal/index.tsx
  src/components/movements-pdf/MovementsPdfDocument.tsx
  src/components/term-modal/index.tsx
  src/pages/equipments/EquipmentsControl.tsx
  src/pages/movements/MovementControl.tsx
  yarn.lock
Labels: FEATURE, US, MDS, MINOR RELEASE

#39 #125 FIX: Componente de Controlled Select
  src/components/equipment-edit-form/index.tsx
  src/components/equipment-edit-modal/index.tsx
  src/components/equipment-form/index.tsx
  src/components/equipment-view-form/index.tsx
  src/components/equipment-view-modal/index.tsx
  src/components/form-fields/equipment/equipment-form.tsx
  src/components/form-fields/new-controlled-select/index.tsx
  src/components/form-fields/new-controlled-select/new-controlled-select.spec.tsx
  src/components/movement-form/index.tsx
  src/components/movements-modal/index.tsx
  src/pages/equipments/EquipmentsControl.tsx
  src/pages/movements/MovementControl.tsx
  src/pages/order-service/OrderServiceControl.tsx
Labels: HOTFIX, MEDIUM, EPS, FIX RELEASE

#40 128 - criação da tela de realizar login
  src/App.tsx
  src/components/side-bar/index.tsx
  src/config/routes/Routes.tsx
  src/config/routes/require-auth.tsx
  src/contexts/AuthContext.tsx
  src/pages/login/AlectrionIcon.tsx
  src/pages/login/index.tsx
  src/types/auth.d.ts
Labels: MDS

#42 fix: lint quebrado
  src/components/movements-pdf/MovementsPdfDocument.tsx
Labels: MINOR RELEASE

#41 114 fix: campos cadastro equipamento
  src/components/equipment-edit-form/index.tsx
  src/components/equipment-edit-modal/index.tsx
  src/components/equipment-form/index.tsx
  src/components/equipment-view-form/index.tsx
  src/components/equipment-view-modal/index.tsx
  src/components/form-fields/equipment/edit-equipment-form.tsx
  src/components/movement-form/index.tsx
  src/components/movements-pdf/MovementsPdfDocument.tsx
  src/pages/edit-equipment/edit-equipment-modal.tsx
  src/pages/equipments/EquipmentsControl.tsx
  src/pages/movements/MovementControl.tsx
  src/services/requests/equipment/types.d.ts
Labels: MINOR RELEASE

#37 101 cadastro ordem servico
  src/components/order-service-register-form/index.tsx
  src/components/order-service-register-modal/index.tsx
  src/constants/user.tsx
  src/pages/order-service/OrderServiceControl.tsx
  src/styles/react-datepicker.scss
Labels: FEATURE, HARD, MINOR RELEASE

#48 126 tela cadastro usuario
  src/components/side-bar/index.tsx
  src/config/routes/Routes.tsx
  src/constants/user.tsx
  src/pages/user-register/UserRegister.spec.tsx
  src/pages/user-register/UserRegister.tsx
  src/types/usuarios.d.ts
Labels: FEATURE, US, HARD, MDS, MINOR RELEASE

#47 136 alterar senha de login
  src/config/routes/Routes.tsx
  src/pages/login/index.tsx
  src/pages/password-recover/PasswordRecover.tsx
  src/pages/password-recover/password-recover.spec.tsx
  src/types/usuarios.d.ts
Labels: FEATURE, US, MDS, MINOR RELEASE

#51 127 visualizar perfil usuario
  src/components/form-fields/equipment/edit-equipment-form.tsx
  src/components/side-bar/index.tsx
  src/config/routes/Routes.tsx
  src/contexts/AuthContext.tsx
  src/pages/change-password/index.tsx
  src/pages/edit-equipment/edit-equipment-modal.tsx
  src/pages/edit-equipment/index.tsx
  src/pages/view-profile/ViewProfileControl.tsx
  src/types/auth.d.ts
  yarn.lock
Labels: FEATURE, US, MINOR RELEASE

#46 134 fix: responsavel atribuicao
  src/components/movement-form/index.tsx
Labels: HOTFIX, EASY, EPS, FIX RELEASE

#50 #137 FIX: Corrige data e cor da tabela de OS
  src/constants/orderservice.ts
  src/pages/order-service/OrderServiceControl.tsx
Labels: EASY, FIX RELEASE

#43 130 fix: pegando a quantidade correta de equipamentos
  src/components/movement-form/index.tsx
Labels: HOTFIX, EASY, EPS, MAJOR RELEASE

#52 fix: env
  .env.example
Labels: FIX RELEASE

#53 135 adicionando termo de ordem de serviço
  src/components/order-service-pdf/index.tsx
  src/components/order-service-register-form/index.tsx
  src/components/order-service-register-modal/index.tsx
  src/components/order-service-term-modal/index.tsx
  src/pages/order-service/OrderServiceControl.tsx
  src/pages/order-service/orderservice.spec.tsx
Labels: EASY, MDS, MINOR RELEASE
