Repository fga-eps-mds/2023-1-Alectrion-FrontEnd, pull requests merged in 2023-07, with the labels that each got.

#57 FIX: Adição de lib para report de duração de teste
  package.json
  sonar-project.properties
  vitest.config.ts
Labels: HOTFIX, DEVOPS, EPS

#58 150 - Criar múltiplos equipamentos
  package.json
  src/components/equipment-register-modal/index.tsx
  src/components/equipment-upload-modal/index.tsx
  src/components/modal/index.tsx
  src/pages/equipments/EquipmentsControl.tsx
Labels: US, MDS, MINOR RELEASE

#64 163 - Aumentando cobertura de testes
  src/components/action-buttons/delete-extensive-button/delete-button.spec.tsx
  src/components/action-buttons/delete-extensive-button/delete-extensive-button.spec.tsx
  src/components/equipment-edit-form/equipment-edit-form.spec.tsx
  src/components/equipment-edit-form/index.tsx
  src/components/equipment-form/equipment-form.spec.tsx
  src/components/equipment-form/index.tsx
  src/components/equipment-view-form/equipment-view-form.spec.tsx
  src/components/movement-form/movement-form.spec.tsx
  src/components/order-service-edit-form/index.tsx
  src/components/order-service-edit-form/order-service-edit-form.spec.tsx
  src/components/order-service-register-form/index.tsx
Labels: MDS, tests

#65 138 feat: cadastro marca e tipo
  src/components/edit-brands-form/index.tsx
  src/components/edit-type-form/index.tsx
  src/components/equipment-edit-form/index.tsx
  src/components/equipment-form/index.tsx
  src/components/equipment-view-form/index.tsx
  src/components/movement-form/index.tsx
  src/components/movements-modal/index.tsx
  src/components/movements-pdf/MovementsPdfDocument.tsx
  src/components/order-service-edit-form/index.tsx
  src/components/order-service-pdf/index.tsx
  src/components/order-service-register-form/index.tsx
  src/components/side-bar/index.tsx
  src/config/routes/Routes.tsx
  src/pages/equipments-fields/EquipmentsFields.tsx
  src/pages/equipments/EquipmentsControl.tsx
  src/pages/movements/MovementControl.tsx
  src/pages/order-service/OrderServiceControl.tsx
Labels: MEDIUM, EPS, MINOR RELEASE

#62 154 listagem de usuario
  package.json
  src/components/action-buttons/delete-extensive-icon/index.tsx
  src/components/equipment-edit-form/equipment-edit-form.spec.tsx
  src/components/equipment-form/equipment-form.spec.tsx
  src/components/equipment-view-form/equipment-view-form.spec.tsx
  src/components/movement-form/movement-form.spec.tsx
  src/components/order-service-edit-form/order-service-edit-form.spec.tsx
  src/components/side-bar/index.tsx
  src/components/user-edit-form/index.tsx
  src/components/user-edit-modal/index.tsx
  src/components/user-register-form/index.tsx
  src/components/user-register-modal/index.tsx
  src/config/routes/Routes.tsx
  src/constants/user.tsx
  src/contexts/AuthContext.tsx
  src/pages/user-register/UserRegister.spec.tsx
  src/pages/user-register/UserRegister.tsx
  src/pages/users/UsersControl.tsx
  src/pages/users/usersControl.spec.tsx
  yarn.lock
Labels: EPS, MDS, MINOR RELEASE

#71 151 gerar relatorios equipamento 2
  package.json
  src/components/equipment-edit-form/index.tsx
  src/components/equipment-view-form/equipment-view-form.spec.tsx
  src/components/equipment-view-form/index.tsx
  src/components/movement-form/movement-form.spec.tsx
  src/components/order-service-edit-form/order-service-edit-form.spec.tsx
  src/components/report-modal/document.tsx
  src/components/report-modal/index.tsx
  src/config/lib/axios/index.ts
  src/config/routes/Routes.tsx
  src/pages/equipments/EquipmentsControl.tsx
  src/services/requests/equipment/index.tsx
  src/utils/filterEquipmentData.ts
  src/utils/format-date.ts
  yarn-error.log
  yarn.lock
Labels: FEATURE, HARD, MINOR RELEASE

#69 FIX: Correção de verificação de token expirado
  src/config/routes/Routes.tsx
  src/config/routes/require-auth.tsx
  src/contexts/AuthContext.tsx
Labels: HOTFIX, EASY, EPS, FIX RELEASE

#73 142 gerar relatorios de movimentacoes
  src/components/form-fields/date/index.tsx
  src/components/movements-reports/pdf/document.tsx
  src/components/movements-reports/pdf/index.tsx
  src/components/order-service-pdf/index.tsx
  src/constants/movements.ts
  src/pages/movements/MovementControl.tsx
  src/styles/react-datepicker.scss
  src/utils/getMovements.ts
  yarn.lock
Labels: US, MDS, MAJOR RELEASE

#74 fix: movements blank page after register
  src/components/movement-form/index.tsx
  src/components/movements-modal/index.tsx
  src/components/movements-pdf/MovementsPdfDocument.tsx
  src/components/side-bar/index.tsx
  src/pages/reports/Reports.tsx
Labels: HOTFIX
